schema_version = "1.0.0"
id = "theme_white"
name = "White"
version = "1.0.0"
tagline = "Community-made theme"
maintainer = "Community"
type = "theme"
tags = ["Light", "High Contrast"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-2.0-or-later"]
website = "https://projects.blender.org/extensions/theme_white"
